// <auto-generated />
namespace _14DTHC34Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialASPNETIdentiyTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialASPNETIdentiyTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201709270253579_InitialASPNETIdentiyTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
